export const personalInfo = {
  name: "Jess Anthony M. Tahil",
  nickname: "Sej",
  title: "Full-Stack Developer & IT Graduate",
  headline: "Building digital experiences that matter",
  subtitle: "Full-Stack Developer crafting elegant, performant applications with modern technologies",
  email: "jesstahil10@gmail.com",
  location: "Philippines",
  resumeUrl: "/files/Tahil,%20Jess%20Anthony%20M.%20-%20Resume.pdf",
  github: "https://github.com/SoulSej10",
  linkedin: "https://www.linkedin.com/in/jess-anthony-tahil-46a442197/",
  about: [
    "An Information Technology graduate passionate about building intuitive and purposeful digital experiences. With a strong foundation in full-stack development, I specialize in creating applications that are not only functional but delightful to use.",
    "During my academic journey and internship, I honed backend skills using .NET, developed cross-platform mobile apps with Flutter and Xamarin, and built responsive web experiences with React, Next.js, and Tailwind CSS.",
    "I thrive on collaborating on meaningful projects, learning emerging technologies, and creating tools that bring real value to users. Whether through efficient code, thoughtful architecture, or seamless user experiences—I strive to deliver work that speaks for itself.",
    "When I'm not coding, you'll find me exploring ideas on freelancing, business, and tech innovations that solve real-world problems."
  ],
  quickFacts: [
    { label: "Based in", value: "Philippines" },
    { label: "Degree", value: "BS Information Technology" },
    { label: "Available", value: "Open to Opportunities" },
    { label: "Focus", value: "Full-Stack Development" },
  ],
  stats: [
    { label: "Projects Completed", value: 15, suffix: "+" },
    { label: "Technologies Used", value: 30, suffix: "+" },
    { label: "GitHub Repositories", value: 20, suffix: "+" },
    { label: "Years Learning", value: 4, suffix: "+" },
  ],
}

export const experience = [
  {
    id: 1,
    role: "IT Intern",
    company: "DICT Region 10",
    period: "2024",
    description: "Gained hands-on experience in web development, system maintenance, and IT support. Worked on internal tools and collaborated with the development team.",
    type: "internship" as const,
    technologies: [".NET", "React", "SQL Server", "Git"],
  },
  {
    id: 2,
    role: "Full-Stack Developer (Freelance)",
    company: "Self-Employed",
    period: "2023 - Present",
    description: "Developing custom web applications for clients. Building responsive frontends with React/Next.js and robust backends with Node.js and .NET.",
    type: "freelance" as const,
    technologies: ["React", "Next.js", "Node.js", "Tailwind CSS", "TypeScript"],
  },
  {
    id: 3,
    role: "BS Information Technology",
    company: "University of Science and Technology of Southern Philippines",
    period: "2020 - 2025",
    description: "Graduated with a degree in Information Technology. Focused on software development, database management, and web technologies.",
    type: "education" as const,
    technologies: ["C#", "Java", "Python", "SQL", "Web Development"],
  },
  {
    id: 4,
    role: "Mobile App Developer (Academic Project)",
    company: "USTP",
    period: "2023",
    description: "Led the development of a cross-platform mobile application using Flutter. Implemented RESTful API integration and state management.",
    type: "project" as const,
    technologies: ["Flutter", "Dart", "Firebase", "REST APIs"],
  },
  {
    id: 5,
    role: "Certification: Responsive Web Design",
    company: "freeCodeCamp",
    period: "2023",
    description: "Completed the Responsive Web Design certification, mastering HTML, CSS, Flexbox, CSS Grid, and responsive design principles.",
    type: "certification" as const,
    technologies: ["HTML", "CSS", "Flexbox", "CSS Grid"],
  },
]

export const skillCategories = [
  {
    title: "Frontend",
    icon: "code",
    skills: [
      { name: "React", level: 85, years: 2 },
      { name: "Next.js", level: 80, years: 2 },
      { name: "TypeScript", level: 75, years: 2 },
      { name: "JavaScript", level: 90, years: 3 },
      { name: "HTML/CSS", level: 95, years: 4 },
      { name: "Tailwind CSS", level: 90, years: 2 },
      { name: "Bootstrap", level: 85, years: 3 },
    ],
  },
  {
    title: "Backend",
    icon: "server",
    skills: [
      { name: "ASP.NET", level: 80, years: 2 },
      { name: ".NET Core", level: 78, years: 2 },
      { name: "RESTful API", level: 85, years: 3 },
      { name: "Django", level: 70, years: 1 },
      { name: "Node.js", level: 65, years: 1 },
      { name: "Python", level: 75, years: 2 },
    ],
  },
  {
    title: "Mobile",
    icon: "smartphone",
    skills: [
      { name: "Flutter", level: 75, years: 2 },
      { name: "Dart", level: 70, years: 2 },
      { name: "Xamarin", level: 60, years: 1 },
    ],
  },
  {
    title: "Database",
    icon: "database",
    skills: [
      { name: "SQL", level: 85, years: 3 },
      { name: "MongoDB", level: 70, years: 2 },
      { name: "Firebase", level: 75, years: 2 },
    ],
  },
  {
    title: "DevOps & Cloud",
    icon: "cloud",
    skills: [
      { name: "Git", level: 90, years: 3 },
      { name: "CI/CD", level: 70, years: 1 },
      { name: "AWS", level: 60, years: 1 },
      { name: "Azure", level: 55, years: 1 },
    ],
  },
  {
    title: "Tools & Design",
    icon: "palette",
    skills: [
      { name: "Figma", level: 70, years: 2 },
      { name: "Postman", level: 85, years: 3 },
      { name: "Swagger", level: 75, years: 2 },
      { name: "VS Code", level: 95, years: 4 },
    ],
  },
]

export const projects = [
  {
    title: "E-Portfolio Website",
    description: "A personal portfolio website showcasing my background, achievements, and projects. Built with modern web technologies for optimal performance and aesthetics.",
    longDescription: "This portfolio was designed to be a comprehensive showcase of my development journey. Featuring a premium dark theme, smooth animations, and responsive design, it demonstrates my ability to build polished, production-quality applications.",
    tech: ["Next.js", "Tailwind CSS", "TypeScript", "Framer Motion"],
    category: "Web Development",
    status: "Live",
    year: "2026",
    link: "https://my-eportfolio-two.vercel.app/",
    github: "https://github.com/SoulSej10/My-Eportfolio",
    features: [
      "Premium dark theme design",
      "Smooth page transitions & animations",
      "Responsive across all devices",
      "Contact form with email integration",
    ],
  },
  {
    title: "StocklaneOS",
    description: "A modern inventory management system with real-time tracking, analytics, and intelligent stock management capabilities.",
    longDescription: "StocklaneOS is a comprehensive inventory management solution designed for businesses of all sizes. It features real-time stock tracking, detailed analytics dashboards, and intelligent reordering suggestions to streamline operations.",
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "Vercel"],
    category: "Full-Stack Application",
    status: "Live",
    year: "2026",
    link: "https://frontend-nu-smoky-44.vercel.app/",
    github: "",
    features: [
      "Real-time inventory tracking",
      "Analytics & reporting dashboard",
      "Intelligent stock alerts",
      "Responsive management interface",
    ],
    isFeatured: true,
  },
  {
    title: "Taccuino",
    description: "A sleek, feature-rich note-taking application with markdown support, organization tools, and seamless cross-device sync.",
    longDescription: "Taccuino is a flagship note-taking application that combines beautiful design with powerful functionality. It offers markdown editing, notebook organization, and seamless synchronization across devices, making it the perfect tool for capturing and organizing ideas.",
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "Vercel"],
    category: "Full-Stack Application",
    status: "Live",
    year: "2025",
    link: "https://taccuino-iota.vercel.app/",
    github: "",
    features: [
      "Rich markdown editor",
      "Notebook organization system",
      "Cross-device sync",
      "Clean, distraction-free interface",
    ],
    isFeatured: true,
  },
  {
    title: "Gazetta",
    description: "A social media post scheduler that automates content generation with OpenAI and automates posting workflows with n8n.",
    longDescription: "Gazetta (SMP Post Scheduler) automates social media postings end-to-end — integrating OpenAI to generate on-brand content and n8n to orchestrate the backend scheduling and publishing flow.",
    tech: ["Next.js", "OpenAI API", "n8n", "Tailwind CSS"],
    category: "Full-Stack Application",
    status: "Live",
    year: "2025",
    link: "https://smp-post-scheduler.vercel.app",
    github: "https://github.com/SoulSej10/SMP-Post-Scheduler",
    features: [
      "AI-generated social media content",
      "Automated posting via n8n workflows",
      "Multi-platform scheduling",
      "Clean scheduling dashboard",
    ],
    isFeatured: true,
  },
  {
    title: "CipherLab",
    description: "A Django web application deployed on PythonAnywhere demonstrating core full-stack development skills.",
    longDescription: "CipherLab is a web application built with Django that showcases proficiency in both backend and frontend development. It demonstrates database integration, user authentication, and responsive design patterns.",
    tech: ["Python", "Django", "HTML", "CSS", "JavaScript"],
    category: "Web Development",
    status: "Live",
    year: "2025",
    link: "https://jessanthony10.pythonanywhere.com/",
    github: "",
    features: [
      "Django backend architecture",
      "User authentication system",
      "Database integration",
      "Responsive frontend design",
    ],
  },
]
